# Generated by Django 5.2 on 2025-05-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_client_created_at_client_password_produit_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_subadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
